# Generated by Django 5.1 on 2024-10-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='checkpoints',
            new_name='trackdata',
        ),
    ]
